# Generated by Django 4.1.5 on 2023-01-09 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('steam_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerRankInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match_data.player')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_averge', models.FloatField()),
                ('rank_variance', models.FloatField()),
                ('player_1', models.ManyToManyField(related_name='player_1', to='match_data.playerrankinstance')),
                ('player_2', models.ManyToManyField(related_name='player_2', to='match_data.playerrankinstance')),
                ('player_3', models.ManyToManyField(related_name='player_3', to='match_data.playerrankinstance')),
                ('player_4', models.ManyToManyField(related_name='player_4', to='match_data.playerrankinstance')),
                ('player_5', models.ManyToManyField(related_name='player_5', to='match_data.playerrankinstance')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demo_url', models.CharField(max_length=200)),
                ('datetime', models.DateTimeField()),
                ('team_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_1', to='match_data.team')),
                ('team_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_2', to='match_data.team')),
            ],
        ),
    ]
