# Generated by Django 4.1.5 on 2023-01-09 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='match_history_key',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Matchcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchcode', models.CharField(max_length=200)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match_data.player')),
            ],
        ),
    ]
